name: Deploy to Firebase Hosting on merge
on:
  push:
    branches:
      - main
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest 
    steps:
      # Checkout the repository
      - uses: actions/checkout@v4
      
      # Install dependencies and build the project
      - name: Install dependencies
        run: npm install
      
      - name: Build project
        run: npm run build
      
      # Deploy to Firebase Hosting
      - name: Deploy to Firebase
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_ULTOFCOM }}
          channelId: live
          projectId: ultofcom
